### ISSUE TITLE
NMS fro YOLOv8

### ISSUE THREAD

**Issue by piotr-sikora-v** [akbartus/Yolov8-Object-Detection-on-Browser#1]
first of all greate job!

do you have any simple how-to get NMS from yolov8?

**Comment by akbartus** [comment]
You need to use onnx graph surgeon. But here is the link for python code created by Wahyu Setianto which you can use: https://github.com/Hyuto/fun/tree/master/test-onnx-graph-surgeon. Use [nms-onnx-v8.py](https://github.com/Hyuto/fun/blob/master/test-onnx-graph-surgeon/nms-onnx-v8.py)

**Comment by piotr-sikora-v** [comment]
Big thanks!
