### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by chih3b** [akbartus/Yolov8-Object-Detection-on-Browser#2]
Code work very slow.how can we optimize it?

**Comment by akbartus** [comment]
@chih3b Onnx implementation of YOLOv8 is slower indeed. One way to increase the speed/inference is to reduce the size of the model. Originally it is 640x640. In this repo it is 416x416. You can make 320x320. Another option is to use TFLite version or TFJS version of YOLOv8. I already posted example for YOLOv8 TFJS implementation. See "tfjs_version".

Let me know if this helps.
