### ISSUE TITLE
Custom YOLO model

### ISSUE THREAD

**Issue by darich10** [akbartus/Yolov8-Object-Detection-on-Browser#3]
Hello, 

Thanks for your contribution. I am trying to implement a custom model with a different number of classes but I'm not sure where to apply my changes. Could you help me with this process? 

Thanks in advance.

**Comment by akbartus** [comment]
@darich10 thank you for your kind question. You can learn custom model implementation here: https://blog.roboflow.com/how-to-train-yolov8-on-a-custom-dataset/. Basically you need to generate model, indicate path to it, then replace classes in this code.

Alternatively I added tensorflow.js implementation. The only difference is that you convert your custom model to tfjs model. 

I hope this helps.
