### ISSUE TITLE
tfjs dont work

### ISSUE THREAD

**Issue by chih3b** [akbartus/Yolov8-Object-Detection-on-Browser#4]
the onnx version dont work but tfjs dont work.how to fix it?

**Comment by akbartus** [comment]
@chih3b thanks for the feedback. Could you be more specific and tell what does not work?

**Comment by chih3b** [comment]
i tired your link and it dont work:https://pickle-pinto-feverfew.glitch.me/tfjs_version/ .plust how do i ran the code after i download it.is there a document or something about the steps?.thank you for being helpful

**Comment by akbartus** [comment]
Just tested the code works fine. You just need to wait for a few seconds as it loads model first and then starts tracking. As for documentation, check here: https://github.com/ultralytics/ultralytics and here: https://docs.ultralytics.com/integrations/tfjs/

**Comment by akbartus** [comment]
Closing issue. Assume it was resolved.
